# Site
name: "Giftable"
title: "Giftable"
description: "Life is short. Time is fast. So enjoy every moment as it comes."
logo: 'assets/images/Logo_fullsize.png'
favicon: 'assets/images/favicon_giftable.ico'
baseurl: 'https://giftable.blog'
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: huynhnt135@gmail.com

# Authors
authors:
  darius:
    name: Darius
    display_name: Darius
    avatar: 'assets/images/avatar-sal.png'
    email: huynhnt135@gmail.com
    web: 
    twitter: https://twitter.com/huynhtroc
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 100
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
